// Versioned Trouble Brewing script definition (docs/01 §6, docs/03 §6).
//
// The exact Operational orders live here (not in UI code) and are
// snapshot-tested. Occurrence metadata drives the queue builder.

import type { CharacterId } from "./characters";

export type StepKind =
  | "POISONER_CHOOSE"
  | "WASHERWOMAN_INFO"
  | "LIBRARIAN_INFO"
  | "INVESTIGATOR_INFO"
  | "CHEF_INFO"
  | "EMPATH_INFO"
  | "FORTUNE_TELLER_CHOOSE"
  | "FORTUNE_TELLER_INFO"
  | "SPY_GRIMOIRE"
  | "BUTLER_CHOOSE"
  | "BUREAUCRAT_CHOOSE"
  | "MONK_CHOOSE"
  | "IMP_CHOOSE"
  | "IMP_KILL"
  | "UNDERTAKER_INFO"
  | "RAVENKEEPER_CHOOSE"
  | "RAVENKEEPER_INFO";

export type StepActor = "PLAYER" | "STORYTELLER";
export type Occurrence = "FIRST_CYCLE_ONLY" | "EACH_CYCLE" | "NOT_FIRST_CYCLE" | "TRIGGERED";

export const STEP_CHARACTER: Record<StepKind, CharacterId> = {
  POISONER_CHOOSE: "POISONER",
  WASHERWOMAN_INFO: "WASHERWOMAN",
  LIBRARIAN_INFO: "LIBRARIAN",
  INVESTIGATOR_INFO: "INVESTIGATOR",
  CHEF_INFO: "CHEF",
  EMPATH_INFO: "EMPATH",
  FORTUNE_TELLER_CHOOSE: "FORTUNE_TELLER",
  FORTUNE_TELLER_INFO: "FORTUNE_TELLER",
  SPY_GRIMOIRE: "SPY",
  BUTLER_CHOOSE: "BUTLER",
  BUREAUCRAT_CHOOSE: "BUREAUCRAT",
  MONK_CHOOSE: "MONK",
  IMP_CHOOSE: "IMP",
  IMP_KILL: "IMP",
  UNDERTAKER_INFO: "UNDERTAKER",
  RAVENKEEPER_CHOOSE: "RAVENKEEPER",
  RAVENKEEPER_INFO: "RAVENKEEPER",
};

export const STEP_ACTOR: Record<StepKind, StepActor> = {
  POISONER_CHOOSE: "PLAYER",
  WASHERWOMAN_INFO: "STORYTELLER",
  LIBRARIAN_INFO: "STORYTELLER",
  INVESTIGATOR_INFO: "STORYTELLER",
  CHEF_INFO: "STORYTELLER",
  EMPATH_INFO: "STORYTELLER",
  FORTUNE_TELLER_CHOOSE: "PLAYER",
  FORTUNE_TELLER_INFO: "STORYTELLER",
  SPY_GRIMOIRE: "STORYTELLER",
  BUTLER_CHOOSE: "PLAYER",
  BUREAUCRAT_CHOOSE: "PLAYER",
  MONK_CHOOSE: "PLAYER",
  IMP_CHOOSE: "PLAYER",
  IMP_KILL: "STORYTELLER",
  UNDERTAKER_INFO: "STORYTELLER",
  RAVENKEEPER_CHOOSE: "PLAYER",
  RAVENKEEPER_INFO: "STORYTELLER",
};

export const STEP_OCCURRENCE: Record<StepKind, Occurrence> = {
  POISONER_CHOOSE: "EACH_CYCLE",
  WASHERWOMAN_INFO: "FIRST_CYCLE_ONLY",
  LIBRARIAN_INFO: "FIRST_CYCLE_ONLY",
  INVESTIGATOR_INFO: "FIRST_CYCLE_ONLY",
  CHEF_INFO: "FIRST_CYCLE_ONLY",
  EMPATH_INFO: "EACH_CYCLE",
  FORTUNE_TELLER_CHOOSE: "EACH_CYCLE",
  FORTUNE_TELLER_INFO: "EACH_CYCLE",
  SPY_GRIMOIRE: "EACH_CYCLE",
  BUTLER_CHOOSE: "EACH_CYCLE",
  BUREAUCRAT_CHOOSE: "EACH_CYCLE",
  MONK_CHOOSE: "NOT_FIRST_CYCLE",
  IMP_CHOOSE: "NOT_FIRST_CYCLE",
  IMP_KILL: "NOT_FIRST_CYCLE",
  UNDERTAKER_INFO: "NOT_FIRST_CYCLE",
  RAVENKEEPER_CHOOSE: "TRIGGERED",
  RAVENKEEPER_INFO: "TRIGGERED",
};

export interface ScriptDefinition {
  id: "TROUBLE_BREWING";
  version: number;
  firstOperationalOrder: StepKind[];
  otherOperationalOrder: StepKind[];
}

export const TROUBLE_BREWING_SCRIPT_ID = "TROUBLE_BREWING";
export const TROUBLE_BREWING_SCRIPT_VERSION = 1;

export const TROUBLE_BREWING: ScriptDefinition = {
  id: TROUBLE_BREWING_SCRIPT_ID,
  version: TROUBLE_BREWING_SCRIPT_VERSION,
  firstOperationalOrder: [
    "POISONER_CHOOSE",
    "WASHERWOMAN_INFO",
    "LIBRARIAN_INFO",
    "INVESTIGATOR_INFO",
    "CHEF_INFO",
    "EMPATH_INFO",
    "FORTUNE_TELLER_CHOOSE",
    "FORTUNE_TELLER_INFO",
    "SPY_GRIMOIRE",
    "BUTLER_CHOOSE",
    "BUREAUCRAT_CHOOSE",
  ],
  otherOperationalOrder: [
    "POISONER_CHOOSE",
    "MONK_CHOOSE",
    "EMPATH_INFO",
    "FORTUNE_TELLER_CHOOSE",
    "FORTUNE_TELLER_INFO",
    "SPY_GRIMOIRE",
    "BUTLER_CHOOSE",
    "IMP_CHOOSE",
    "IMP_KILL",
    "UNDERTAKER_INFO",
    "BUREAUCRAT_CHOOSE",
  ],
};

export function getScriptDefinition(id: string, version: number): ScriptDefinition {
  if (id === TROUBLE_BREWING.id && version === TROUBLE_BREWING.version) {
    return TROUBLE_BREWING;
  }
  throw new Error(`Unknown script ${id}@${version}`);
}
