// Canonical domain event type names for Slice 1 (docs/04 §7).
// No magic strings elsewhere in domain code.

export const EVENTS = {
  GAME_CREATED: "GAME_CREATED",
  PLAYER_ADDED: "PLAYER_ADDED",
  PLAYER_UPDATED: "PLAYER_UPDATED",
  PLAYER_REMOVED: "PLAYER_REMOVED",
  VIRTUAL_CIRCLE_REORDERED: "VIRTUAL_CIRCLE_REORDERED",
  PLAYER_CLAIM_TOKEN_ISSUED: "PLAYER_CLAIM_TOKEN_ISSUED",
  PLAYER_CLAIMED: "PLAYER_CLAIMED",
  PLAYER_SESSION_REVOKED: "PLAYER_SESSION_REVOKED",
  // Setup / roles (Slice 2)
  SETUP_GENERATED: "SETUP_GENERATED",
  SETUP_COMMITTED: "SETUP_COMMITTED",
  ROLE_REVEALED_TO_PLAYER: "ROLE_REVEALED_TO_PLAYER",
  TRAVELLER_ALIGNMENT_ASSIGNED: "TRAVELLER_ALIGNMENT_ASSIGNED",
  // Operational (Slice 2)
  OPERATIONAL_STARTED: "OPERATIONAL_STARTED",
  ACTION_QUEUE_BUILT: "ACTION_QUEUE_BUILT",
  PLAYER_ACTION_SUBMITTED: "PLAYER_ACTION_SUBMITTED",
  STORYTELLER_DECISION_RECORDED: "STORYTELLER_DECISION_RECORDED",
  PRIVATE_INFORMATION_DELIVERED: "PRIVATE_INFORMATION_DELIVERED",
  OPERATIONAL_COMPLETED: "OPERATIONAL_COMPLETED",
  INVESTIGATION_STARTED: "INVESTIGATION_STARTED",
} as const;

export type EventType = (typeof EVENTS)[keyof typeof EVENTS];
