// Canonical domain event type names for Slice 1 (docs/04 §7).
// No magic strings elsewhere in domain code.

export const EVENTS = {
  GAME_CREATED: "GAME_CREATED",
  PLAYER_ADDED: "PLAYER_ADDED",
  PLAYER_UPDATED: "PLAYER_UPDATED",
  PLAYER_REMOVED: "PLAYER_REMOVED",
  VIRTUAL_CIRCLE_REORDERED: "VIRTUAL_CIRCLE_REORDERED",
  PLAYER_CLAIM_TOKEN_ISSUED: "PLAYER_CLAIM_TOKEN_ISSUED",
  PLAYER_CLAIMED: "PLAYER_CLAIMED",
  PLAYER_SESSION_REVOKED: "PLAYER_SESSION_REVOKED",
  // Setup / roles (Slice 2)
  SETUP_GENERATED: "SETUP_GENERATED",
  SETUP_COMMITTED: "SETUP_COMMITTED",
  ROLE_REVEALED_TO_PLAYER: "ROLE_REVEALED_TO_PLAYER",
  TRAVELLER_ALIGNMENT_ASSIGNED: "TRAVELLER_ALIGNMENT_ASSIGNED",
  // Operational (Slice 2)
  OPERATIONAL_STARTED: "OPERATIONAL_STARTED",
  ACTION_QUEUE_BUILT: "ACTION_QUEUE_BUILT",
  PLAYER_ACTION_SUBMITTED: "PLAYER_ACTION_SUBMITTED",
  STORYTELLER_DECISION_RECORDED: "STORYTELLER_DECISION_RECORDED",
  PRIVATE_INFORMATION_DELIVERED: "PRIVATE_INFORMATION_DELIVERED",
  OPERATIONAL_COMPLETED: "OPERATIONAL_COMPLETED",
  INVESTIGATION_STARTED: "INVESTIGATION_STARTED",
  // Death / effects / role change (Slice 3)
  DEATH_ATTEMPTED: "DEATH_ATTEMPTED",
  DEATH_PREVENTED: "DEATH_PREVENTED",
  DEATH_REDIRECTED: "DEATH_REDIRECTED",
  PLAYER_DIED: "PLAYER_DIED",
  TRIGGERED_ACTION_CREATED: "TRIGGERED_ACTION_CREATED",
  CHARACTER_CHANGED: "CHARACTER_CHANGED",
  EFFECT_APPLIED: "EFFECT_APPLIED",
  EFFECT_EXPIRED: "EFFECT_EXPIRED",
  DEMON_SUCCESSION_RESOLVED: "DEMON_SUCCESSION_RESOLVED",
  // Investigation / voting / execution / victory (Slice 4)
  NOMINATIONS_OPENED: "NOMINATIONS_OPENED",
  NOMINATION_CREATED: "NOMINATION_CREATED",
  VIRGIN_TRIGGER_RESOLVED: "VIRGIN_TRIGGER_RESOLVED",
  SLAYER_USED: "SLAYER_USED",
  VOTE_INTENT_RECORDED: "VOTE_INTENT_RECORDED",
  VOTE_LOCKED: "VOTE_LOCKED",
  GHOST_VOTE_CONSUMED: "GHOST_VOTE_CONSUMED",
  NOMINATION_RESOLVED: "NOMINATION_RESOLVED",
  PLAYER_EXECUTED: "PLAYER_EXECUTED",
  TRAVELLER_EXILED: "TRAVELLER_EXILED",
  NOMINATIONS_CLOSED: "NOMINATIONS_CLOSED",
  INVESTIGATION_COMPLETED: "INVESTIGATION_COMPLETED",
  GAME_ENDED: "GAME_ENDED",
  // Scenario (Slice 5)
  QR_SCANNED: "QR_SCANNED",
  CLUE_DISCOVERED: "CLUE_DISCOVERED",
  TASK_STARTED: "TASK_STARTED",
  TASK_COMPLETED: "TASK_COMPLETED",
  SCENARIO_STAGE_CHANGED: "SCENARIO_STAGE_CHANGED",
  MAP_UNLOCKED: "MAP_UNLOCKED",
  SCENARIO_CONDITION_APPLIED: "SCENARIO_CONDITION_APPLIED",
  SCENARIO_CONDITION_CLEARED: "SCENARIO_CONDITION_CLEARED",
  SCENARIO_OVERRIDE_APPLIED: "SCENARIO_OVERRIDE_APPLIED",
} as const;

export type EventType = (typeof EVENTS)[keyof typeof EVENTS];
